config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :articles

  get "/users", to: "users#index"

  get "/users/show:id", to: "users#show", as: "user_show"

  root 'users#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  belongs_to :user  

  validates :title, :content, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :articles , dependent: :destroy

  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  

	before_filter :configure_permitted_parameters, if: :devise_controller?

	  def configure_permitted_parameters

	    devise_parameter_sanitizer.for(:sign_up) do |u|

	      u.permit(:name, :email, :password)

	    end

	    devise_parameter_sanitizer.for(:account_update) do |u|

	      u.permit(:name, :email, :password, :current_password, :avatar)

	    end

	  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_filter :find_article, except: [:index, :new, :create ]
  
  def index
    @articles = Article.all
  end
  
  def show
    
  end
  
  def new
  	@article = Article.new
  end

  def create

    @article = Article.new(article_params)

    @article.user = current_user

    if @article.save
    	redirect_to @article
    	flash[:notice] = "Successfully created..."
    else
    	render  :new
    	flash[:error] = @article.errors.full_messages.to_sentence
    end

  end
  
  def edit
    
  end
  
  def update
  	@article = Article.find(params[:id])
  	
  	if @article.update(article_params)
  		redirect_to @article
  		flash[:notice] = "Successfully updated..."
  	else
  		render :edit
  		flash[:error] = @article.errors.full_messages.to_sentence
  	end

  end

  def destroy
    
    if @article.destroy
    	redirect_to article_path method: :delete
    	flash[:notice] = "Successfully deleted..."
    end

  end

  private 

    def article_params
    	params.require(:article).permit(:title, :content)
    end

    def find_article
    	@article = Article.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/_form.html.erb
<h2>Create Article</h2>

<%= form_for @article do |f| -%>

	<div class="field">
	  <%= f.label :title, "Title" %><br />
	  <%= f.text_field :title %>
	</div>

	<div class="field">
	  <%= f.label :content, "Content" %><br />
	  <%= f.text_area :content %>
	</div>

	<div class="field">
		<%= f.submit "Submit", :disable_with => 'Submiting...' %>
	</div>

<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <%= article.title %>
  <%= article.content %>
  <%= article.user_id %>
  <%= link_to 'delete', article_path(article), data: {confirm: "Are you sure"}, method: :delete %>
  <br />
<% end %>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<%= @article.title %><br />
<%= @article.content %><br/>
<%= @article.user_id %><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BlogApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">BlogApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.name %>
  <%= user.email %>
  <%= link_to 'delete', edit_user_registration_path(method: :delete) %>
  <%= link_to 'view', user_show_path(user) %>
  <br />
<% end %>

app/views/users/show.html.erb
<%= @user.name %>
<%= @user.email %>

<%= link_to 'Edit Profile', edit_user_registration_path %>